### PR TITLE
Introduce `command line usage` for default command

### PR DESCRIPTION
**Pull request by yjaeseok**
I would like to show command line usage when user type just 
```./bacardi```

So I add command-line-usage package for generate usage contents 
and then add implement usage in default.

After this patch user can see like below :

```shell
jakeMacAir:bacardi jakeyoon$ ./bacardi 
[22:17:23] Requiring external module ts-node/register
[22:17:24] Using gulpfile ~/Workspace/yjaeseok/bacardi/gulpfile.ts
[22:17:24] Starting 'default'...

Bacardi

  Bacardi project is an effort to provide multi-language binding for
  Node.js native layer.

Synopsis

  $ bacardi <command> 

Available Commands

  build            Builds bacardi project             
  build_electron   Builds bacardi project as electron 
  electron         Runs bacardi project as electron   
  test             Runs Unit test bacardi project     
[22:17:24] Finished 'default' after 6.99 ms
jakeMacAir:bacardi jakeyoon$ 
```

### CODE REVIEW

**Comment by nadongguri** [comment]
It's good to me but will be better seperate it to another file like[polymer-cli](https://github.com/Polymer/polymer-cli/blob/master/src/commands/help.ts) :-).

**Comment by yjaeseok** [comment]
@nadongguri Ofcourse I refer to Polymer CLI
But... this patch is for just introduce !!
So I would like to discuss about this today :)

**Comment by romandev** [comment]
%s/bacard/bacardi/g (in your commit description)

**Comment by yjaeseok** [comment]
I updated it :)

**Review by romandev — COMMENTED** [review]
lgtm with nit.
Commit description should be < 72 byte.
So, I modified your commit description.

**Review by romandev — APPROVED** [review]

**Pull request merged**
