### PR TITLE
Remove DefinitionType enum.

### PR DESCRIPTION
**Pull request by hwanseung**
Definition Type is not necessary in order to figure out type.
because we can use ```instanceof``` keyword in typescript.
and i think this keyword is more clearly better than to check ```type``` attribute of Definition.

ISSUE=None

### CODE REVIEW

**Comment by hwanseung** [comment]
we already used ```instanceof``` keyword twice in order to type check.
https://github.com/lunchclass/bacardi/blob/master/generator/main.ts#L48
https://github.com/lunchclass/bacardi/blob/master/generator/main.ts#L90

**Review by yjaeseok — APPROVED** [review]
lgtm !

**Comment by yjaeseok** [comment]
@daehyunjimmy , I think you can remove ```instance of``` keyword after merge.!

**Review by romandev — APPROVED** [review]
lgtm

**Pull request merged**
