### PR TITLE
Separate test and format command in develop

### PR DESCRIPTION
**Pull request by yjaeseok**
Because we generally do not want to check formatting
during test. In other words, most of the developers
just want to test it only with test command.

So I separate test and format command in development
environment. But CI test should run with format
test.

As a result, developers can test only with test command
in development environment.
When developer want to pull request, they must fix
formatting issue.

ISSUE=#155

### CODE REVIEW

**Comment by yjaeseok** [comment]
I included format errors for test. After checking that an error has occurred, it will be removed.

**Comment by yjaeseok** [comment]
https://travis-ci.org/lunchclass/bacardi/builds/297182701?utm_source=github_status&utm_medium=notification

https://ci.appveyor.com/project/romandev/bacardi/build/1.0.266

is failed , because we need to fix formatting issue.

**Comment by yjaeseok** [comment]
PTAL!! @romandev @hwanseung @byeolbit

**Comment by hwanseung** [comment]
um.. did not we decided to separate format command from test command?
so i thought to remove formatting code from test script and add format script  at .appveyor.yml and .travis.yml.

**Comment by yjaeseok** [comment]
@hwanseung 
format command is for formatting. So if i add format command to .appveyor.yml. It seems to do format.

But test command means that we want to test. 
I think in CI environment, we want to unit test and format test. In development environment, we want to unit test only.

So I do this..! How do you think?

**Comment by yjaeseok** [comment]
I add lint command ! Please review @hwanseung @romandev

**Review by romandev — APPROVED** [review]
lgtm

**Pull request merged**
