### PR TITLE
Add byte and octet types

### PR DESCRIPTION
**Pull request by daehyunjimmy**
Need to support byte and octet basic types.
  - Byte (int8_t) - the byte type is a signed integer type that has
    values in the range [-128, 127].
  - Octet (uint8_t) - the octet type is an unsigned integer type that
    has values in the range [0, 255].

ISSUE=#150

### CODE REVIEW

**Review by romandev — COMMENTED** [review]
Please write some tests for this patch into test/interface_basic_types.test.ts instead of modifying examples/*.

**Review by romandev — COMMENTED** [review]
Also, please file a bug before starting work. Then, we can reduce duplicated efforts.

**Review by romandev — COMMENTED** [review]
Please write a commit description in more details.
Especially, it should be as follows:
```
Your commit description.

ISSUE=#<Your issue number>
```

**Comment by yjaeseok** [comment]
lgtm

**Review by romandev — APPROVED** [review]
lgtm

**Pull request merged**
