### PR TITLE
Add github pull request template

### PR DESCRIPTION
**Pull request by yjaeseok**
We do not have github a pull request template,
User can write pull request freely.
So I would like to add a pull request template.

ISSUE=#176

### CODE REVIEW

**Comment by nadongguri** [comment]
Wow, you found it. LGTM. :D
How do you think giving more info like as below?
- First letter should be capital.
- one line shouldn't exceed 72 bytes.

**Comment by nadongguri** [comment]
In addition, there are many good things we can apply. :D 
[Github building a strong community](https://help.github.com/categories/building-a-strong-community/).
Thanks again.

**Comment by yjaeseok** [comment]
@nadongguri Thanks for your review.
IMHO Your suggestions are probably something to add to CONTRIBUTING.md files. 

This is for only pull request body template. So I would like to do not add guideline in the body.
How do you think?

**Comment by yjaeseok** [comment]
@nadongguri please refer to https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by yjaeseok** [comment]
@romandev please review

**Comment by romandev** [comment]
@yjaeseok,
IMHO, I'm not sure if it's a good idea to put this template in.
If your patch is applied, when creating a pull request, the template will overwrite original commit description.
I think it might provide a bad UX for contributos.

For example, I usually using a Vim editor in my case.
Then, I will check line-break-rule for commit description(<72bytes) and send a pull request.
BTW, the commit description will be overwritten due to pull_request_template.md.
So, I'll have to fix the commit description again.

WDYT?

**Comment by romandev** [comment]
@yjaeseok I think we need ```issue_template.md``` as well. (or only need it)
Also, I'd prefer to putting the template files into ```docs/``` and using lower cases as an file name.

**Comment by yjaeseok** [comment]
OMG!! @romandev your opinion is good!!!
I was not worried about your opinion !

As you mention, pull request template make you uncomfortable. 

But I will consider how to force our rule (eg: title is must be under 72 bytes, add issue number) when writing my first commit description in Vim editor.

Thank you for your opinion.

Maybe I seem to have focused too much on one commit. ;(

**Comment by romandev** [comment]
@yjaeseok Thank you for understanding me :)
IMHO, we still needs issue_template.md and it's very useful to us, I think!

**Pull request closed without merging**
