### PR TITLE
use Assert module[1] instead of console log.

### PR DESCRIPTION
**Pull request by hwanseung**
this Assert module is a default module of node.js.
so it does not need to additional install.

[1] https://nodejs.org/api/assert.html

### CODE REVIEW

**Review by romandev — APPROVED** [review]
lgtm

**Review by romandev — CHANGES_REQUESTED** [review]
Ah, sorry. lgtm but please update your name and email in AUTHORS file in this patch. :)

**Comment by hwanseung** [comment]
i did update my information in AUTHORS files.

**Review by romandev — APPROVED** [review]
lgtm

**Pull request merged**
