### PR TITLE
Replace mocha with jest for test

### PR DESCRIPTION
**Pull request by hwanseung**
Replace mocha with jest for test
 - replace tests using jest
 - remove mocha module from package.json

ISSUE=#99

### CODE REVIEW

**Comment by yjaeseok** [comment]
it also has travis error

**Comment by romandev** [comment]
IMHO, we should replace the example tests with feature tests in test/ directory.
In example directory, we should leave only actual example.

**Comment by hwanseung** [comment]
@romandev 
yes i know that we told about it. i just want to remove mocha module in our project.

**Comment by nadongguri** [comment]
The error from the travis seems to be trivial because it was just failed to clone the bacardi repository in Mac.

**Pull request merged**
